"use client";

import { FormEvent, useState } from "react";
import { Star } from "lucide-react";
import { submitPublicReview } from "@/app/review/actions";

export function PublicReviewForm({ token, projectName, recipientName }: { token: string; projectName: string | null; recipientName: string | null }) {
  const [rating, setRating] = useState(5);
  const [message, setMessage] = useState<string | null>(null);
  const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); const data = new FormData(event.currentTarget); setBusy(true); const result = await submitPublicReview({ token, name: String(data.get("name") ?? ""), email: String(data.get("email") ?? ""), rating, testimonial: String(data.get("testimonial") ?? "") }); setBusy(false); setMessage(result.ok ? "Thank you—your review was received and will be published after Creatiq reviews it." : result.error); if (result.ok) event.currentTarget.reset(); }
  return <main className="flex min-h-screen items-center justify-center bg-[radial-gradient(circle_at_top,rgba(8,189,255,.16),transparent_32rem),#020b1f] p-4"><form onSubmit={submit} className="glass-card w-full max-w-xl rounded-3xl p-6 sm:p-8"><p className="text-[10px] font-bold uppercase tracking-[.22em] text-secondary">Creatiq customer review</p><h1 className="mt-3 text-3xl font-black tracking-[-.04em] text-primary">How was your experience{recipientName ? `, ${recipientName}` : ""}?</h1><p className="mt-3 text-sm leading-6 text-muted">{projectName ? `Your feedback about ${projectName} helps us improve and helps future clients choose Creatiq with confidence.` : "Your feedback helps us improve and helps future clients choose Creatiq with confidence."}</p><div className="mt-6"><p className="text-[10px] font-bold uppercase tracking-widest text-secondary">Your rating</p><div className="mt-2 flex gap-2">{[1, 2, 3, 4, 5].map((star) => <button key={star} type="button" onClick={() => setRating(star)} className={star <= rating ? "text-amber-200" : "text-muted/30"} aria-label={`${star} star rating`}><Star size={28} fill="currentColor" /></button>)}</div></div><div className="mt-5 grid gap-4 sm:grid-cols-2"><Input label="Your name" name="name" required /><Input label="Email address" name="email" type="email" required /></div><label className="mt-4 block"><span className="text-[10px] font-bold uppercase tracking-widest text-secondary">Your review</span><textarea name="testimonial" required minLength={20} maxLength={2000} className="mt-1.5 min-h-36 w-full rounded-xl border border-cyan-300/15 bg-background/60 p-3 text-sm text-primary outline-none focus:border-secondary" placeholder="Tell us about working with Creatiq..." /></label><button disabled={busy} className="primary-btn mt-6 h-12 w-full rounded-xl text-xs font-black uppercase tracking-widest text-white disabled:opacity-60">{busy ? "Submitting..." : "Submit review"}</button>{message && <p className="mt-4 text-center text-sm leading-6 text-secondary" aria-live="polite">{message}</p>}</form></main>;
}
function Input({ label, name, type = "text", required = false }: { label: string; name: string; type?: string; required?: boolean }) { return <label className="block"><span className="text-[10px] font-bold uppercase tracking-widest text-secondary">{label}</span><input name={name} type={type} required={required} className="mt-1.5 h-11 w-full rounded-xl border border-cyan-300/15 bg-background/60 px-3 text-sm text-primary outline-none focus:border-secondary" /></label>; }
