import { CalendarCheck, LayoutDashboard, Package, type LucideIcon } from "lucide-react";

const solutions: { title: string; description: string; icon: LucideIcon }[] = [
  { title: "Booking Systems", description: "Streamlined scheduling for service-based businesses.", icon: CalendarCheck },
  { title: "Inventory Management", description: "Real-time tracking, stock visibility, and automated stock alerts.", icon: Package },
  { title: "Custom Dashboards", description: "Data visualization for faster and smarter decision-making.", icon: LayoutDashboard },
];

export function SolutionsSection() { return <section className="relative overflow-hidden py-20 sm:py-24 lg:py-32"><div className="mx-auto grid max-w-7xl items-center gap-12 px-4 sm:px-6 lg:grid-cols-2 lg:gap-20 lg:px-10 xl:px-16"><DashboardPreview /><div className="space-y-7 sm:space-y-8"><h2 className="text-3xl font-bold text-primary md:text-4xl">Advanced Enterprise Solutions</h2><p className="text-base leading-8 text-muted sm:text-lg">We specialize in building custom digital systems that simplify business operations, improve workflow, and make daily processes more efficient.</p><ul className="space-y-5 sm:space-y-6">{solutions.map(({ title, description, icon: Icon }) => <li key={title} className="flex items-start gap-4"><span className="shrink-0 rounded-lg bg-cyan-300/10 p-2 text-secondary"><Icon size={24} /></span><div><h3 className="text-lg font-bold text-foreground">{title}</h3><p className="mt-1 text-sm leading-6 text-muted">{description}</p></div></li>)}</ul></div></div></section>; }

function DashboardPreview() { return <div className="relative order-2 mx-auto w-full max-w-xl lg:order-1"><div className="absolute -inset-8 rounded-full bg-secondary/10 blur-[80px]" /><div className="glass-card tech-grid relative z-10 rounded-3xl p-4 shadow-[0_0_50px_rgba(8,189,255,0.2)] sm:p-6"><div className="rounded-2xl border border-white/10 bg-[#061a3a]/80 p-5 sm:p-6"><div className="mb-6 flex items-start justify-between gap-4 sm:mb-8"><div><p className="text-xs font-bold uppercase tracking-widest text-secondary">Enterprise Suite</p><h3 className="mt-2 text-xl font-bold text-primary sm:text-2xl">Business Control Center</h3></div><LayoutDashboard className="shrink-0 text-secondary" size={30} /></div><div className="grid gap-3 sm:grid-cols-2 sm:gap-4"><Metric label="Projects" value="24" /><Metric label="Requests" value="138" /><div className="rounded-2xl bg-indigo-300/10 p-5 sm:col-span-2"><div className="mb-4 h-3 w-4/5 rounded-full bg-cyan-300/30" /><div className="h-3 w-3/5 rounded-full bg-cyan-300/20" /></div></div></div></div></div>; }
function Metric({ label, value }: { label: string; value: string }) { return <div className="rounded-2xl bg-cyan-300/10 p-5"><p className="text-sm text-muted">{label}</p><p className="mt-2 text-3xl font-bold text-secondary">{value}</p></div>; }
