import { BarChart3, CheckCircle2, CircleGauge, Users } from "lucide-react";
import { getAdminWorkspace, getDashboardMetrics } from "@/lib/crm/admin-data";

export default async function ReportsPage() {
  const workspace = await getAdminWorkspace();
  const metrics = getDashboardMetrics(workspace);
  const cards = [{ label: "30-day inquiry volume", value: metrics.recentInquiries, icon: BarChart3, detail: "New conversations captured from the website." }, { label: "Inquiry conversion", value: `${metrics.conversionRate}%`, icon: CircleGauge, detail: `${metrics.converted} inquiry conversions to date.` }, { label: "Task completion", value: `${metrics.taskCompletion}%`, icon: CheckCircle2, detail: "Completed tasks across the available workspace." }, { label: "Active employees", value: workspace.profiles.filter((profile) => profile.is_active).length, icon: Users, detail: "People available for project assignments." }];
  return <section className="space-y-6"><div><p className="text-[10px] font-bold uppercase tracking-[0.22em] text-secondary">Studio intelligence</p><h1 className="mt-2 text-3xl font-black tracking-[-0.04em] text-primary sm:text-4xl">Reports</h1><p className="mt-2 max-w-2xl text-sm leading-6 text-muted">A focused first-release report suite: pipeline, delivery completion, conversion, overdue work, and workload.</p></div><div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-4">{cards.map(({ label, value, icon: Icon, detail }) => <article key={label} className="rounded-2xl border border-cyan-300/15 bg-surface/60 p-5"><Icon size={19} className="text-secondary" /><p className="mt-5 text-[10px] font-bold uppercase tracking-widest text-muted">{label}</p><p className="mt-2 text-3xl font-black text-primary">{value}</p><p className="mt-3 text-xs leading-5 text-muted">{detail}</p></article>)}</div><div className="grid gap-5 xl:grid-cols-[1.2fr_.8fr]"><article className="rounded-2xl border border-cyan-300/15 bg-surface/60 p-5 sm:p-6"><h2 className="text-lg font-black text-primary">Project pipeline</h2><div className="mt-5 space-y-3">{metrics.pipeline.map((stage) => <div key={stage.status}><div className="flex justify-between text-sm"><span className="font-semibold text-primary">{stage.status.replaceAll("_", " ")}</span><span className="text-secondary">{stage.count}</span></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-primary/10"><div className="h-full rounded-full bg-secondary" style={{ width: `${workspace.projects.length ? (stage.count / workspace.projects.length) * 100 : 0}%` }} /></div></div>)}</div></article><article className="rounded-2xl border border-cyan-300/15 bg-surface/60 p-5 sm:p-6"><h2 className="text-lg font-black text-primary">Employee workload</h2><div className="mt-5 space-y-3">{metrics.workload.map((member) => <div key={member.name} className="flex items-center justify-between rounded-xl bg-background/30 p-3"><div><p className="font-semibold text-primary">{member.name}</p><p className="mt-1 text-xs text-muted">{member.overdueTasks ? `${member.overdueTasks} overdue` : "On track"}</p></div><p className="text-xl font-black text-secondary">{member.openTasks}</p></div>)}</div></article></div></section>;
}
