import { ResourceManager, type ResourceRow } from "@/components/admin/resource-manager";
import { requireAdmin } from "@/lib/crm/auth";
import { getAdminWorkspace } from "@/lib/crm/admin-data";

export default async function PortfolioPage() {
  await requireAdmin(["OWNER"]);
  const workspace = await getAdminWorkspace();
  return <ResourceManager resource="portfolio" title="Portfolio" description="Publish the work that should appear on the public Creatiq website. Uploading stores visual media in Cloudinary." rows={workspace.portfolio.map((project) => ({ ...project, technologies: project.technologies.join(", ") })) as unknown as ResourceRow[]} canCreate canDelete columns={[{ key: "title", label: "Project" }, { key: "category", label: "Category" }, { key: "project_date", label: "Date" }, { key: "is_published", label: "Published" }, { key: "sort_order", label: "Order" }]} fields={[{ name: "title", label: "Project title", required: true }, { name: "slug", label: "URL slug", required: true, hint: "Lowercase words separated with hyphens." }, { name: "category", label: "Category", required: true }, { name: "summary", label: "Summary", type: "textarea", required: true }, { name: "project_url", label: "Live project / repository URL" }, { name: "technologies", label: "Technologies", hint: "Separate technologies with commas." }, { name: "project_date", label: "Project date" }, { name: "asset_size", label: "Original asset size" }, { name: "source_image_path", label: "Original image path", hint: "Preserved source path; upload a Cloudinary image to publish it." }, { name: "image_url", label: "Portfolio image", type: "image-upload" }, { name: "image_public_id", label: "Cloudinary public ID" }, { name: "sort_order", label: "Display order", type: "number", required: true, defaultValue: 0 }, { name: "is_published", label: "Publish to public site", type: "checkbox", defaultValue: false }, { name: "is_featured", label: "Feature this project", type: "checkbox", defaultValue: false }]} />;
}
