import { ResourceManager, type ResourceRow } from "@/components/admin/resource-manager";
import { ProjectDocuments } from "@/components/admin/project-documents";
import { getAdminWorkspace } from "@/lib/crm/admin-data";
import { PROJECT_STATUSES } from "@/lib/crm/constants";

export default async function ProjectsPage() {
  const workspace = await getAdminWorkspace();
  const isOwner = workspace.identity.role === "OWNER";
  const projectRows = workspace.projects.map((project) => ({ ...project, member_ids: workspace.projectMembers.filter((member) => member.project_id === project.id).map((member) => member.profile_id) }));
  const standardFields = [{ name: "name", label: "Project name", required: true }, { name: "description", label: "Project brief", type: "textarea" as const }, { name: "client_id", label: "Client", type: "select" as const, options: workspace.clients.map((client) => ({ value: client.id, label: client.company_name })) }, { name: "status", label: "Stage", type: "select" as const, required: true, options: PROJECT_STATUSES.map((status) => ({ value: status, label: status.replaceAll("_", " ") })) }, { name: "progress", label: "Progress (%)", type: "number" as const, required: true, defaultValue: 0 }, { name: "start_date", label: "Start date", type: "date" as const }, { name: "due_date", label: "Due date", type: "date" as const }, { name: "member_ids", label: "Assigned team", type: "multi-select" as const, options: workspace.profiles.filter((profile) => profile.is_active).map((profile) => ({ value: profile.id, label: `${profile.full_name}${profile.job_title ? ` — ${profile.job_title}` : ""}` })), hint: "Use Ctrl/Cmd to select multiple team members." }];
  return <div className="space-y-6"><ResourceManager resource="projects" title="Projects" description={isOwner ? "Create a project, place it in the delivery pipeline, and assign the people responsible for its outcome." : "Update progress on the projects assigned to you. Core project records remain protected by the Owner role."} rows={projectRows as unknown as ResourceRow[]} canCreate={isOwner} canDelete={isOwner} columns={[{ key: "name", label: "Project" }, { key: "status", label: "Stage", kind: "status" }, { key: "progress", label: "Progress", kind: "progress" }, { key: "due_date", label: "Due", kind: "date" }]} fields={isOwner ? standardFields : [{ name: "status", label: "Stage", type: "select", required: true, options: PROJECT_STATUSES.map((status) => ({ value: status, label: status.replaceAll("_", " ") })) }, { name: "progress", label: "Progress (%)", type: "number", required: true }]} /><ProjectDocuments projects={workspace.projects} documents={workspace.documents} /></div>;
}
